blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Request or Idea
    url: https://github.com/CrewMate-Flight-Sim/CrewMateA350/discussions/categories/ideas
    about: Please post feature requests and ideas in our Discussions tab
  - name: 💬 General Discussion
    url: https://github.com/CrewMate-Flight-Sim/CrewMateA350/discussions/categories/general
    about: Ask questions and discuss Crewmate A350 with the community